In [6]:
import numpy as np
import matplotlib.pyplot as plt
import time
%matplotlib inline


# Problem 1: Solving Matrix manually

$A = \begin{bmatrix}
-1 & 2 & 3\\
4 & -5 & 6\\
7 & 8 & -9
\end{bmatrix}  $

$ B = \begin{bmatrix}
0 & 2 & 1\\
0 & 2 & -8\\
2 & 9 & -1
\end{bmatrix}  $

We solve Matric Product as followed:
As Matrix A stays in form $[ 3 \times 3 ]$ and Matrix B also stay in the similar form, C, product of A and B will stay in form $[ 3 \times 3 ]$ 

We have following formula to calculate Matrix C:

$C_{ij} = A_{i1}B_{1j} \times A_{i2}B_{2j} \times A_{i3}B_{3j} \times  \cdots A_{in}B_{nj} = \sum_{k = 1}^{n}A_{ik}B_{kj}$

Where: 
 - i: stand for $i^{th}$ row
 - j: stand for $j^{th}$ column


Similarly, our product is solved as below:

$ C =  \begin{bmatrix}
-1 \times 0 + 2 \times 0 + 3 \times 2 & -1 \times 2 + 2 \times 2 + 3 \times 9 & -1 \times 1 + 2 \times -8 + 3 \times -1 \\
4 \times 0 + -5 \times 0 + 6 \times 2 & 4 \times 2 + -5 \times 2 + 6 \times 9 & 4 \times 1 + -5 \times -8 + 6 \times -1  \\
7 \times 0 + 8 \times 0 + -9 \times 2  & 7 \times 2 + 8 \times 2 + -9 \times 9  & 7 \times 1 + 8 \times -8 + -9 \times -1 
\end{bmatrix} = 
\begin{bmatrix}   
    6 & 29 & -20 \\
    12 & 52 & 38 \\
    -18 & -51 & -48 
\end{bmatrix}
$

# Problem 2: Matrix product by numpy 

In [10]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

def product_matrix(a_ndarray, b_ndarray):
    nd_array_matmul = np.matmul(a_ndarray, b_ndarray)
    nd_array_dot = np.dot(a_ndarray, b_ndarray)
    nd_array_at = a_ndarray@b_ndarray
    
    return nd_array_matmul, nd_array_dot, nd_array_at

nd_array_matmul, nd_array_dot, nd_array_at = product_matrix(a_ndarray, b_ndarray)

print("C Matric using numpy.matmul: \n {}".format(nd_array_matmul))
print("C Matric using numpy.dot: \n {}".format(nd_array_dot))
print("C Matric using @ : \n {}".format(nd_array_at))

C Matric using numpy.matmul: 
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
C Matric using numpy.dot: 
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
C Matric using @ : 
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# Problem 3: Implementation of calculation of a certain element

In [32]:
def mul_certain_ele(row_of_a = 0, col_of_b = 0):
    mul_00 = (a_ndarray[row_of_a]*b_ndarray[:, col_of_b]).sum()
    return mul_00

row_of_a = 0
col_of_b = 0
print("Mul of row {}th a and column {}th b is: {} ".format(row_of_a, col_of_b, mul_certain_ele(0, 0)))


Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a

Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a

Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a

Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a

Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a

Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a

Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a

Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a

Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a

Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a

Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a

Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a

Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a

Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a

Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a and column 0th b is: 6 
Mul of row 0th a

Another way to perform this is:

In [31]:
mul_00_1 = 0 
for k in range(a_ndarray.shape[1]):
    mul_00_1 += a_ndarray[0, k]*b_ndarray[k, 0]

print(mul_00_1)

6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6


6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6


# Problem 4: Creating a function that performs matrix multiplication

3
