# Introduction to numpy 2

In [1]:
import numpy as np

### Element retrieval

In [2]:
sample_ndarray = np.arange(10)
print(sample_ndarray[3])
print(sample_ndarray[:3])
print(sample_ndarray[-1])
print(sample_ndarray[::2])
print(sample_ndarray[::-1]) # reversed array

3
[0 1 2]
9
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]


### Transforming the shape

In [4]:
a_ndarray = np.arange(4)
print(a_ndarray)
print(a_ndarray.shape)
b_ndarray = a_ndarray.reshape(2, 2)
print(b_ndarray)
print(b_ndarray.shape)

[0 1 2 3]
(4,)
[[0 1]
 [2 3]]
(2, 2)


### Extraction of elements in multiple dimensions

In [8]:
sample_ndarray = np.arange(6).reshape(2, 3)
print(sample_ndarray)
print(sample_ndarray[0, 2])
print(sample_ndarray[:, 1:])

[[0 1 2]
 [3 4 5]]
2
[[1 2]
 [4 5]]


### Average or sum

In [10]:
a_ndarray = np.arange(6)
b_ndarray = a_ndarray.reshape(2, 3)
print("Shape is {}".format(b_ndarray.shape))
print("The total value is {}".format(b_ndarray.sum()))
print("The total in the 0th axial direction is {}".format(b_ndarray.sum(axis=0)))
print("The average in the first axial direction is {}".format(b_ndarray.mean(axis=1)))

Shape is (2, 3)
The total value is 15
The total in the 0th axial direction is [3 5 7]
The average in the first axial direction is [1. 4.]
