# Introduction to numpy 1

In [2]:
import numpy as np

### np.array()

In [3]:
sample_ndarray = np.array([1, 2, 3])
print(sample_ndarray)

[1 2 3]


In [4]:
sample_ndarray = np.array([[1, 2, 3], [4, 5, 6]])
print(sample_ndarray)

[[1 2 3]
 [4 5 6]]


### Array arithmetic operation

In [7]:
print(2 + np.array([1, 2, 3]))

[3 4 5]


In [8]:
print(np.array([2, 2, 2]) + np.array([1, 2, 3]))

[3 4 5]


In [9]:
print(np.array([1, 2, 3]) * np.array([1, 2, 3]))
print(np.array([1, 2, 3]) > np.array([2, 2, 2]))

[1 4 9]
[False False  True]


In [10]:
print(np.array([2]) + np.array([1, 2, 3]))

[3 4 5]


### Sequence information

In [11]:
print(np.array([1, 2, 3]).ndim)
print(np.array([1, 2, 3]).shape)
print(np.array([1, 2, 3]).dtype)

1
(3,)
int32


### np.arange()

In [13]:
sample_ndarray = np.arange(50)
print(sample_ndarray)
print(sample_ndarray.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
(50,)


In [16]:
sample_ndarray = np.arange(50, 100, 2)
print(sample_ndarray)
print(sample_ndarray.shape)

[50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96
 98]
(25,)


### np.ones(), np.zeros(), np.full()

In [19]:
sample_ndarray = np.ones(20)
print(sample_ndarray)
print(sample_ndarray.shape)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
(20,)


In [21]:
sample_ndarray = np.zeros(20)
print(sample_ndarray)
print(sample_ndarray.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(20,)


In [24]:
sample_ndarray = np.full(20, 7)
print(sample_ndarray)
print(sample_ndarray.shape)

[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
(20,)
